### ISSUE TITLE
Server crashes in windows in latest version

### ISSUE THREAD

**Issue by vToMy** [gongzhang/procbridge-python#2]
`AttributeError: module 'socket' has no attribute 'AF_UNIX'`
Here:
https://github.com/gongzhang/procbridge-python/blob/master/procbridge/__init__.py#L77

This property doesn't exist when launching the server on windows. I'm using python 3.8.

**Comment by gongzhang** [comment]
I'll fix it. The current version only added Unix Domain Socket feature. You can use the previous one before I commit a fix.

发自我的iPhone

**Comment by royalstream** [comment]
@vToMy I submitted a pull request #3 to fix this.
It got merged today.

**Comment by gongzhang** [comment]
@royalstream Thanks! I am upgrading the pip package.

**Comment by gongzhang** [comment]
`pip install procbridge==1.2.1`

Well done. 😉

**Comment by vToMy** [comment]
Thanks!
